homeassistant:
  # Name of the location where Home Assistant is running
  name: JoliHome
  # Location required to calculate the time the sun rises and sets
  latitude: 56.0945236
  longitude: 12.9165755
  # ,
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # New Names
  customize:
    # Add an entry for each entity that you want to overwrite info for.
    switch.pluggonoff3:
      friendly_name: Kaffekokare
      icon: mdi:coffee
      assumed_state: false
    switch.nexa_pluggonoff1:
      friendly_name: Fönster kök
      icon: mdi:ceiling-light
      assumed_state: false
      # Add an entry to hide items
        # Nexa Remote
    switch.nexaremote1button1:
      hidden: true
    switch.nexaremote1button2:
      hidden: true
    switch.nexaremote1button3:
      hidden: true   
        # Telldus Remote      
    switch.telldus_remote1button1:
      hidden: true
    switch.telldus_remote1button2:
      hidden: true
    switch.telldus_remote1button3:
      hidden: true
      
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret web_base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

ring:
  username: !secret ring_user
  password: !secret ring_password


# sensors
sensor:
  - platform: yr
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume
# Text to speech
tts:
  platform: google
  language: 'sv'

volvooncall:
  username: !secret voc_username
  password: !secret voc_password
  name:
    nhg064: 'Batmobile'

#TelldusLive Account thelink73
tellduslive:
  public_key: !secret tellus_public_key
  private_key: !secret tellus_private_key
  token: !secret tellus_token
  token_secret: !secret tellus_token_secret

#test med spotify
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: plex

group: !include groups.yaml
device_tracker: !include device_tracker.yaml

# TEST

automation: !include automation.yaml


automation old:
- alias: "Coffee: Automatically turn off"
  trigger:
    - platform: state
      entity_id: switch.pluggonoff3
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.coffee_timer
- alias: "Coffee: reset timer"
  trigger:
    - platform: state
      entity_id: switch.pluggonoff3
      to: 'off'
  action:
    - service: script.turn_off
      entity_id: script.coffee_timer
      
script:
  coffee_timer:
    alias: "Coffee Timer"
    sequence:
      - delay: '00:{{ states.input_slider.coffee_run_time.state | int }}:00'
      - service: homeassistant.turn_off
        data:
          entity_id: switch.pluggonoff3

input_slider:
  coffee_run_time:
    name: Coffee Run Time
    initial: 45
    min: 1
    max: 60
    step: 1