homeassistant:
  # Name of the location where Home Assistant is running
  name: JoliHome
  # Location required to calculate the time the sun rises and sets
  latitude: 56.0945236
  longitude: 12.9165755
  # ,
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  #customize:
    # Add an entry for each entity that you want to overwrite.
    #light.gronlampa_vid_tv:
      #friendly_name: Grön lampa vid TV
    #light.lampa_fonster_matbord:
      #friendly_name: Fönsterlampa vid matbord


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: Linkman10
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

ring:
  username: thelink73@gmail.com
  password: MussePigg10


# sensors
sensor:
  - platform: yr
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume
# Text to speech
tts:
  platform: google
  language: 'sv'

volvooncall:
  username: thelink73@gmail.com
  password: MussePigg10
  name:
    nhg064: 'Batmobile'

#TelldusLive Account thelink73
tellduslive:
  public_key: FEHUVEW84RAFR5SP22RABURUPHAFRUNU
  private_key: ZUXEVEGA9USTAZEWRETHAQUBUR69U6EF
  token: 107fb46a587f646023ef28cb7590fd750590a2834
  token_secret: 6ae5df0c49eefded546874c923d8af7f

#test med spotify
media_player:
  - platform: spotify
    client_id: 8ac196bdc56f4cb5881f5403fd926a0a
    client_secret: 681895f8d507498eadceb0fd6430970e
  - platform: plex

group: !include groups.yaml
device_tracker: !include device_tracker.yaml
